import Link from "next/link";

export const metadata = { title: "Terms of Service — EverReach" };

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-12 text-sm leading-relaxed text-text">
      <Link href="/" className="text-primary hover:text-primary-hover">
        ← EverReach
      </Link>

      <h1 className="mt-6 text-2xl font-semibold">Terms of Service</h1>
      <p className="mt-1 text-text-secondary">Last updated: 2 August 2026</p>

      <div className="mt-8 flex flex-col gap-6">
        <section>
          <h2 className="text-base font-semibold">1. Who this agreement is with</h2>
          <p className="mt-2 text-text-secondary">
            EverReach is operated by Eversity Tech LLP (&quot;Eversity&quot;, &quot;we&quot;). These
            terms govern any business (&quot;you&quot;, the &quot;Customer&quot;) that creates an
            account to send and receive messages with its own customers through EverReach.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">2. What EverReach does</h2>
          <p className="mt-2 text-text-secondary">
            EverReach is a unified inbox that connects your Telegram, Email, WhatsApp, Instagram, and
            Voice channels, and can draft AI-generated replies for you to review, edit, and send. You
            remain responsible for every message sent from your account, whether written by you or
            sent from an AI-drafted suggestion you approved.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">3. Your responsibilities</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-text-secondary">
            <li>
              You must have a lawful basis to message every contact you add — EverReach does not
              verify consent on your behalf.
            </li>
            <li>
              WhatsApp messaging is governed by Meta&apos;s policies via our BSP partner (Gupshup);
              violating those policies can get your WhatsApp number suspended independent of anything
              EverReach does.
            </li>
            <li>
              Voice calling is available only through individually-scheduled Reminders to contacts
              already in your system — never as a bulk or cold-calling channel. You are responsible
              for your own compliance with India&apos;s TRAI/DND regulations, including consent,
              registry checks, and permitted calling hours.
            </li>
            <li>You are responsible for keeping your account credentials and connected channel API keys confidential.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold">4. AI-drafted replies</h2>
          <p className="mt-2 text-text-secondary">
            Draft replies are generated by a third-party AI provider based on your Business Profile
            and conversation history. Drafts are never sent automatically — a human must review and
            send. We do not guarantee the accuracy of AI-drafted content.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">5. Fees</h2>
          <p className="mt-2 text-text-secondary">
            Your subscription fee is set out in your onboarding agreement or order form. Third-party
            costs charged directly by WhatsApp/Meta, Twilio, or your own email provider (when you use
            your own API keys) are your responsibility, separate from your EverReach subscription.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">6. Suspension &amp; termination</h2>
          <p className="mt-2 text-text-secondary">
            We may suspend or terminate an account that violates these terms, is used for unlawful
            messaging, or creates abuse risk to our shared infrastructure or other customers. You may
            close your account at any time; we will retain data only as described in the Privacy
            Policy.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">7. Disclaimers &amp; liability</h2>
          <p className="mt-2 text-text-secondary">
            EverReach is provided &quot;as is&quot;. We are not liable for message delivery failures,
            third-party provider outages, or account suspensions imposed by Meta, Twilio, or other
            channel providers.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">8. Governing law</h2>
          <p className="mt-2 text-text-secondary">
            These terms are governed by the laws of India, with courts of competent jurisdiction in
            India having exclusive jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold">9. Contact</h2>
          <p className="mt-2 text-text-secondary">
            Questions about these terms: reach Eversity Tech LLP through your onboarding contact.
          </p>
        </section>
      </div>

      <p className="mt-10 text-xs text-text-muted">
        See also the <Link href="/privacy" className="text-primary hover:text-primary-hover">Privacy Policy</Link>.
      </p>

      <p className="mt-6 text-xs text-text-muted">
        These terms are accurate to how EverReach works today. They should still be reviewed by a
        lawyer familiar with Indian contract and IT law before being relied on as final legal
        documents for paid customers.
      </p>
    </div>
  );
}
